

iris.features.required = CUSTOM_IMAGES

texture.noise= texture/noise.png

image.histX = samplerHistX red_integer r32ui unsigned_int true false 512 1
image.histY = samplerHistY red_integer r32ui unsigned_int true false 512 1
image.warpX = samplerWarpX red r32f float false false 512 1
image.warpY = samplerWarpY red r32f float false false 512 1

image.transmittanceLut = samplerTransmittance rgba rgba32f float false false 256 64
image.skyLut = samplerSky rgba rgba32f float false false 256 128

clouds=off
oldLighting=false
shadow.culling=false
shadow.enabled= true

blend.shadow=off

scale.composite1=0.5
size.buffer.colortex9=0.5 0.5
size.buffer.colortex10=0.25 0.25
size.buffer.colortex11=0.125 0.125
size.buffer.colortex12=0.0625 0.0625

#ifdef BLOOM
    program.composite5.enabled=true
    program.composite6.enabled=true
    program.composite7.enabled=true
    program.composite8.enabled=true
    program.composite9.enabled=true
    program.composite10.enabled=true
#else
    program.composite5.enabled=false
    program.composite6.enabled=false
    program.composite7.enabled=false
    program.composite8.enabled=false
    program.composite9.enabled=false
    program.composite10.enabled=false
#endif