

iris.features.required = CUSTOM_IMAGES

image.histX = samplerHistX red_integer r32ui unsigned_int true false 512 1
image.histY = samplerHistY red_integer r32ui unsigned_int true false 512 1
image.warpX = samplerWarpX red r32f float false false 512 1
image.warpY = samplerWarpY red r32f float false false 512 1

shadow.culling=false
shadow.enabled= true